accountapp/urls.py
from django.urls import path
from accountapp.views import hello_world, AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'accountapp'
urlpatterns = [
    path('hello_world/', hello_world, name='hello_world'),

    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

profileapp/urls.py
app_name = 'profileapp'

urlpatterns =[

]

progmatic/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
]

accountapp/models.py
from django.db import models

# python manage.py makemigrations
# 우리가 models.py에 작성하는 python file을 database와 연결하기 위한 파일로 변환시켜 준다
#python manage.py migrate
#database로 연결 시켜주기 위한 파일을 만들었다면, 그 이후에는 그 파일을 연결 시켜주는 명령어 필요.
#그게 위 명령어

class HelloWorld(models.Model):
    text = models.CharField(max_length= 255, null=False)

profileapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='porfile')

    image = models.ImageField(upload_to='profile/', null=True)
    nickname = models.CharField(max_length=20, unique=True, null=True)
    message = models.CharField(max_lenght=100, null =True)

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm


#상속을 통해서 UserCreationForm에서 사용하는 것과 유사하게 사용
#하지만 그 형태를 똑같이 사용을 하면, 수정칸에서 입력하는 값이 데이터베이스에 저장되는 상황이 발생(문제점)
class AccountUpdateForm(UserCreationForm):
    def __init__(self,*args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].disabled = True
        #여기서 username을 disabled로 만들어 주면서 클릭을 할 수 없게 만들어줌

profileapp/forms.py
from django.forms import ModelForm

from profileapp.models import Profile


class ProfileCreationForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['images', 'nickname', 'message']

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator

from django.views.generic import CreateView, DetailView, UpdateView, DeleteView

from accountapp.decorators import account_ownership_required
from accountapp.forms import AccountUpdateForm
from accountapp.models import HelloWorld


# Create your views here.

@login_required
def hello_world(request):
    if request.method == "POST":

        temp = request.POST.get('hello_world_input')
        #
        # 가져온 데이터를 저장하는 법

        new_hello_world = HelloWorld()
        new_hello_world.text = temp
        new_hello_world.save()

        #데이터베이스에 정보를 가져와서 출력하는 법
        hello_world_list = HelloWorld.objects.all()
        return HttpResponseRedirect(reverse('accountapp:hello_world'))

        # return render(request, 'accountapp/hello_world.html', context={'hello_world_output': new_hello_world})
    else:
        hello_world_list = HelloWorld.objects.all()
        return render(request, 'accountapp/hello_world.html', context={'hello_world_list': hello_world_list})


class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/create.html'

class AccountDetailView(DetailView):
    model = User
    template_name = 'accountapp/detail.html'
    # 방문한 사람의 정보가 아니라, 특정 pk를 가진 사람의 정보를 보여주려면 view에서 제공하는 context_object_name 을 써주면 된다.
    context_object_name = 'target_user'

@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
@method_decorator(account_ownership_required,'post')
@method_decorator(account_ownership_required,'get')
class AccountUpdateView(UpdateView):
    model = User
    form_class = AccountUpdateForm
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/update.html'
    context_object_name = 'target_user'

@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
@method_decorator(account_ownership_required,'post')
@method_decorator(account_ownership_required,'get')
class AccountDeleteView(DeleteView):
    model = User
    success_url = reverse_lazy('accountapp:login')
    template = 'accountapp/delete.html'
    context_object_name = 'target_user'

profileapp/views.py
from django.shortcuts import render

# Create your views here.

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <div style="text-align: center">
        <form action="{% url 'accountapp:create' %}" method="post">
            {%  csrf_token %}
{#            이렇게 해주면 장고 내의 자동적으로 form 부분에 기존의 가지고 있던 것을 출력해줌. 기본 회원가입 형태.#}
{#            {{ form }}#}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dart rounded-pill col-6 mt-3">
        </form>
    </div>
{% endblock %}

accountapp/templates/accountapp/delete.html
{%  extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <div>
        <div>
            <h4>Quit</h4>
        </div>
        <div style="text-align: center; margin: 4rem auto; max-width: 500px ">
            <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
                {% csrf_token %}
{#                {{ form }}#}
                {% bootstrap_form form %}
                <input type="submit" class="btn btn-danger rounded-pill" col-6 mt-4>
            </form>
        </div>
    </div>

{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}

{%  block content %}
    <div>
        <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
            <p>
{#                user로 설정을 해두면 접속한 사람의 내용만 나옴. 우리는 특정 pk를 가진 사람의 페이지를 구현해야함#}
                {{ target_user.date_joined }}
            </p>
            <h2>
                {{ target_user.username }}
            </h2>
{#            본인 페이지에 본인이 들어왔을 때 수정이 가능하게 함#}
            <a href="{% url 'accountapp:update' pk=user.pk %}">
                <p>
                    Change Info
                </p>
            </a>
        </div>
    </div>
{% endblock %}

accountapp/templates/accountapp/hello_world.html
{% extends 'base.html' %}

{% block content %}
    <div style="border-radius: 1rem; margin: 2rem;text-align : center">
        <h1>
            testing
        </h1>
{#        데이터를 보내는 방법- form태그로 감싸주고 보낼 곳을 명시한다. #}
{#        views.py를 거쳐서 렌더링 하게 된다.#}

        <form action="/account/hello_world/" method="post">
            {%  csrf_token %}
            <div>
                <input type="text" name="hello_world_input">
            </div>
            <div>
                <input type="submit" class="btn btn-primary" value="POST">
            </div>
        </form>

        {%  if hello_world_list  %}
            {%  for hello_world in hello_world_list %}
                <h4>
{#                    {{ hello_world_output.text }}#}
                    {{ hello_world.text }}
                </h4>
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}

accountapp/templates/accountapp/login.html
{%  extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <div>
        <div>
            <h4>Login</h4>
        </div>
        <div style="text-align: center; margin: 4rem auto; max-width: 500px ">
            <form action="" method="post">
                {% csrf_token %}
{#                {{ form }}#}
                {% bootstrap_form form %}
                <input type="submit" class="btn btn-dark rounded-pill" col-6 mt-4>
            </form>
        </div>
    </div>

{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <div>
        <div class ="mb-4">
            <h4>Change Info</h4>
        </div>
        <form action="{%  url 'accountapp:update' pk=target_user.pk %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}

<body>
    {% include 'header.html' %}

    <hr>
    {% block content %}
    {% endblock %}

    <hr>
    {% include 'footer.html' %}

</body>
</html>

templates/footer.html
<div  style="text-align: center">
    <div>
        <span>공지사항 |</span>
        <span>제휴문의 |</span>
        <span>서비스 소개</span>
    </div>
    <div>
        <h6 style="font-family: 'Kanit', sans-serif;">pragmatic</h6>
    </div>
</div>

templates/head.html
<head>
    <meta charset="UTF-8">
    <title>Pragmatic</title>
    {# bootstrap   #}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    {# google font    #}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kanit&display=swap" rel="stylesheet">

</head>

templates/header.html
 <div style="height: 10rem; background-color : lightblue; border-radius: 1rem; margin: 2rem;">
    <div style="text-align: center">
        <div>
            <h1 style="font-family: 'Kanit', sans-serif;">Pragmatic</h1>
        </div>
        <div>
            <span>nav1</span>
            <span>nav2</span>
            <span>nav3</span>
            {% if not user.is_authenticated %}
                <a href="{% url 'accountapp:login' %}?next={{ request.path }}">
                    <span>login</span>
                </a>
                <a href="{% url 'accountapp:create' %}">
                    <span>SignIn</span>
                </a>
            {% else %}
                <a href="{% url 'accountapp:logout' %}?next={{ request.path }}">
                    <span>logout</span>
                </a>
                <a href="{% url 'accountapp:detail' pk=user.pk %}?next={{ request.path }}">
                    <span>MyPage</span>
                </a>
            {% endif %}
        </div>
    </div>
 </div>